name: linux

on: 
   workflow_dispatch:
#  push:
#  pull_request: 
#  schedule: 
#    - cron: '0 0 1 * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup_build_dir
      run: mkdir buildproducts
    - name: cmake
      working-directory: ./buildproducts
      run: cmake ..
    - name: make
      working-directory: ./buildproducts
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: libepanet-output
        path: /home/runner/work/EPANET/EPANET/buildproducts/
